services:
  firefly:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PLATFORM=linux/amd64
    ports:
      - "8080:8080"
    environment:
      PROPS_sso__framework__adapter: org.opencadc.security.sso.TokenRelay
      CADC_SSO_COOKIE_NAME: "CADC_SSO"
      CADC_SSO_COOKIE_DOMAIN: ".canfar.net"
      CADC_ALLOWED_DOMAIN: ".canfar.net"
      PROPS_FIREFLY_OPTIONS: '{"tap": {"additional": {"services": [{"label": "CADC YouCAT", "value": "https://ws-uv.canfar.net/youcat", "centerWP": "62;-37;EQ_J2000", "fovDeg": 10}]}}}'