apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: set-x-forwarded-proto
  namespace: skaha-workload
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: https
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: firefly-ingress
  namespace: skaha-workload
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  routes:
    - kind: Rule
      match: Host(`rc-uv.canfar.net`) && PathPrefix(`/session/notebook/firefly/`)
      middlewares:
        - name: set-x-forwarded-proto
      services:
        - name: firefly-svc
          port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: firefly-svc
  namespace: skaha-workload
  labels:
    app: firefly-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: firefly-http
  selector:
    canfar-net-sessionID: "firefly"
    canfar-net-sessionName: "firefly"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly-deployment
  namespace: skaha-workload
  labels:
    canfar-net-sessionID: "firefly"
    canfar-net-sessionName: "firefly"
    canfar-net-sessionType: "firefly"
    canfar-net-userid: "tomcat"
spec:
  replicas: 1
  selector:
    matchLabels:
      canfar-net-sessionID: "firefly"
      canfar-net-sessionName: "firefly"
  template:
    metadata:
      labels:
        canfar-net-sessionID: "firefly"
        canfar-net-sessionName: "firefly"
        canfar-net-sessionType: "firefly"
        canfar-net-userid: "tomcat"
    spec:
      restartPolicy: Always
      containers:
        - name: firefly
          image: images.canfar.net/skaha/firefly:dev
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "4Gi"
              cpu: "1"
            limits:
              memory: "8Gi"
              cpu: "2"
          ports:
            - containerPort: 8080
              protocol: TCP
              name: firefly-http
          env:
            - name: DEBUG
              value: "TRUE"
            - name: PROPS_sso__framework__adapter
              value: "org.opencadc.security.sso.TokenRelay"
            - name: CADC_SSO_COOKIE_NAME
              value: "CADC_SSO"
            - name: CADC_SSO_COOKIE_DOMAIN
              value: ".canfar.net"
            - name: CADC_ALLOWED_DOMAIN
              value: ".canfar.net"
            - name: baseURL
              value: "/session/notebook/firefly/"
            - name: "PROPS_FIREFLY_OPTIONS"
              value: >-
                {"tap":
                    {"additional":
                      {"services":[
                        {
                          "label": "CADC YouCAT",
                          "value": "https://ws-uv.canfar.net/youcat",
                          "centerWP": "62;-37;EQ_J2000",
                          "fovDeg": 10
                        }]
                    }
                  }
                }
          # This provides initialDelaySeconds + periodSeconds*failureThreshold seconds, i.e. 5 + 5*5 = 30 seconds
          # for the container port to be ready before the container is considered unhealthy
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
              - curl
              - "-I"
              - "HEAD"
              - "http://localhost:8080/session/notebook/firefly/firefly/"
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
              - curl
              - "-I"
              - "HEAD"
              - "http://localhost:8080/session/notebook/firefly/firefly/"
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 3
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 91
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
